### ISSUE TITLE
[Feature-Request] Implement OAuth2

### ISSUE THREAD

**Issue by thecodrr** [madagaga/WTalk#3]
I think this will take a lot of testing and time but this is necessary. Not every user can use the manual kind of authentication which is now implemented. This will do all the steps automatically, the user will just have to put in the username and password.

Documents for help:
Hangish has it implemented (it's C++): [OAuth2](https://github.com/rogora/hangish/blob/master/oauth2auth.cpp) With a little time, I can try and port it.

There are many libraries for OAuth2 like [DotNetOpenAuth](http://dotnetopenauth.net/) which can help in this process.

**Comment by madagaga** [comment]
Google provides a .net library to authenticate on their server. I didn't use it because I just need oauth and the lib is fat as it handle all the services.

You're right, it would ne cool to have a integrated process. 

If you look at the source there is a screen which was created for this, but I didn't implement all yet.

**Comment by madagaga** [comment]
I'll take a look on hangish implementation.
I've seen all hangups forks but I looked the hangout part only not the auth.

**Comment by thecodrr** [comment]
Yes, you are right. The `AuthWindow` is declared but not implemented completely.

**Comment by madagaga** [comment]
Oauth is now integrated in a windowed webbrowser.

**Comment by thecodrr** [comment]
Let's see what you have done.

**Comment by thecodrr** [comment]
This is better than expected! Well done!
